# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170207_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='upc',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
