# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170209_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
