# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170213_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradas',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
